---
title: "Group by / Summarise"
author: "Hans"
date: "9/10/2019"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(dplyr)
library(tidyverse)

dat <- read.csv("https://raw.githubusercontent.com/guru99-edu/R-Programming/master/lahman-batting.csv")
write.csv(dat, "dat.csv")

dat <- read.csv("dat.csv")

glimpse (dat) %>%
  select(c(playerID, yearID, AB, teamID, lgID, G, R, HR, SH))  %>% 
  arrange(playerID, teamID, yearID) %>% 
  glimpse()
```


It is simple to calculate the mean of a variable, in this case R 

```{r}
summarise(dat, meanR = mean(R))
```

You do not get a value though if there are NA in the variable

```{r}
summarise(dat, meanSH = mean(SH))
```

You  can eliminate them simply 

```{r}
summarise(dat, meanSH = mean(SH, na.rm = TRUE))
```

Showing multiple parameter is possible

```{r}
summarise(dat, 
          mean_games = mean(G),
          mean_SH = mean(SH, na.rm = TRUE))
```


Usually you use a group_by in a summarise

```{r}

dat %>%
	group_by(lgID) %>%
	summarise(mean_run = mean(HR))

```

You can send it to a plot straight away

```{r}

dat %>% 
  group_by(lgID) %>% 
  summarise(mean_home_run = mean(HR)) %>% 
  ggplot(aes(x = lgID, y = mean_home_run, fill = lgID)) +
    geom_bar(stat = "identity") +
    theme_classic() +
    labs(
        x = "baseball league",
        y = "Average home run",
        title = paste("Example group_by() with summarise()"
        )
    )

```

