---
title: "wrangle"
author: "Hans"
date: "9/7/2019"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("pacman")) +
  install.packages("pacman") 
library(pacman)
p_load(tidyverse)
p_load(modelr)
p_load(measurements)
p_load(tidyverse)
p_load(nycflights13)
p_load(dplyr)
p_load(dslabs)
```






# Data frame

```{r}

# stringsAsFactors = FALSE is used to prevent the automatic creation of factors
# For 'sex' you want it, so there you specify it explicitly

mydata <- data.frame(person = c("Peter","Lois","Meg","Chris","Stewie"),
                     age    = c(42,40,17,14,1),
                     sex    = factor(c("M","F","F","M","M")), 
                     stringsAsFactors = FALSE)
mydata
mydata$age
mydata$sex
mydata$person
```

# Tibble

Excerpt From: Tilman M. Davies. “The Book of R”. Apple Books. 
```{r}
head(iris,15)
tib_iris <- as_tibble(iris)
```

```{r}

# Create a 10 row tibble

tibble(
  x = 1:10,
  y = 1,
  z = x^2 +y
)
```

```{r}

# A different method to create a tibble
tribble(
  ~x, ~y, ~z,
  "a", 2, 3.6,
  "b", 1, 8.5)
```


```{r}

# Create a 1000 rowtibble

tibble(
 a = lubridate::now() + runif(1e3) * 86400,
 b = lubridate::today() + runif(1e3) * 30,
 c = 1:1e3,
 d = runif(1e3),
 e = sample(letters, 1e3, replace = TRUE) )
```


```{r}
df <- tibble(
  x = runif(5),
  y = runif(5)
)

df
df$x
df[["x"]]
df[[1]]

```

Loop over the columns in a tibble

```{r}
df <- tibble(
  a = rnorm(10),
  b = rnorm(10),
  c = rnorm(10),
  d = rnorm(10)
)

# Create an empty vector to hold the data
output <- vector("double", ncol(df))

# Then loop
for (i in seq_along(df)) {
  output[[i]]= median(df[[i]])  
}
output
```



```{r}


# Remove the flights that were cancelled 
not_cancelled <- flights %>% 
  filter(!is.na(dep_delay), !is.na(arr_delay))
not_cancelled

# Get the average delay of all flights for each day
avdelay <- not_cancelled %>% 
  group_by(year, month, day) %>% 
  summarise(mean = mean(dep_delay))

avdelay

# ggplot(data = avdelay) +
#   geom_point(mapping = aes(x = year, y = mean))

```


# Detect outlier

```{r}

# The data set contains a big outlier
outlier_example

# You can see that because mean and median differ a lot
mean(outlier_example)
median(outlier_example)

# You can see that also because sd is large
sd(outlier_example)

# You can see that also in the histogram
qplot(outlier_example)

# You can see that also in the boxplot
boxplot(outlier_example)

# See if there are values > 8. See! There is one 180 
outlier_example[outlier_example > 8]

# At what index des it sit?
which(outlier_example > 8)

# Remove it form the dataset
oe <- outlier_example[-which(outlier_example>8)]
mean(oe)
median(oe)
sd(oe)
qplot(oe)
boxplot(oe)

```


# Select

```{r}
iris

# For the selection purpose just consider the first 10 records 
short_iris <- head(iris,10)

select(short_iris, starts_with("Petal"))
select(short_iris, starts_with("Sepal"))
select(short_iris, Species, everything())
select(short_iris, -Sepal.Length)
```

# Filter

```{r}
starwars
class(starwars)

# It works on a dataframe

filter(starwars, species == 'Human')
filter(starwars, mass > 100)
filter(starwars, species == 'Human', mass > 100)
filter(starwars, species == 'Human' & mass > 100)
filter(starwars, species == 'Human' | mass > 100)
filter(starwars, gender == 'female')

# It works just as well on a tibble

tib_starwars = as.tibble(starwars)
class(tib_starwars)
filter(tib_starwars, species == 'Human')
```


```{r}
# install.packages("modelr")
library(modelr)
data(heights)
heights

```

```{r}

h <- heights %>%
  mutate(
    weight_kg_man = weight * 0.453592,
    weight_kg_pkg = conv_unit(weight, "lbs", "kg"),
    height_m = conv_unit(height, "inch", "m")
  ) %>%
  select(starts_with('weight'), starts_with("height"))
h
```

```{r}
my_heights <- heights %>%
  mutate(
    weight = conv_unit(weight, "lbs", "kg"),
    height = conv_unit(height, "inch", "m"),
    bmi = weight / height  ^ 2
  ) %>% select(bmi, education)
my_heights
```

```{r}
h <- my_heights %>%
  arrange(bmi) %>%
  select(bmi, education)
h
```

```{r}
ggplot(h) +
  geom_smooth(mapping = aes (x = bmi, y = education))
```


```{r}
tailnum_delay_db <- flights %>% 
  group_by(tailnum) %>%
  summarise(
    delay = mean(arr_delay, na.rm = TRUE),
    n = n()
  ) %>% 
  arrange(desc(delay)) %>%
  filter(n > 100)

tailnum_delay_db

```


# Spread  and gather
```{r}

# gather and spread worl on a dataframe or tibble
class(ChickWeight)
cw = data.frame(ChickWeight)
cw = as.tibble(ChickWeight)

# The following  are equivalent
(cw_w = spread(data = cw, key = "Time", value = "weight"))
(cw_w = spread(data = cw, key = Time, value = weight))
(cw_w = spread(data = cw, Time, weight))
(cw_w = spread(cw, Time, weight))
(cw_w <- ChickWeight %>% as_tibble %>% 
  spread(-Chick, -Diet))
  
# You explicitly specify the columns to gather
# (cw_l <- gather(data = cw_w, 
#                 key = "Time", 
#                 value = "Weight", 
#                 ... = `0`:`21`,
#                 convert = T, na.rm = T))

# Or you can specify to gather everything except certain columns
(cw_l <- gather(data = cw_w, 
                key = "Time", 
                value = "Weight", 
                -Chick,
                -Diet,
                convert = T, na.rm = T))

(cw_l <- gather(data = cw_w, 
                key = "Time", 
                value = "Weight", 
                c(-Chick, -Diet),
                convert = T, na.rm = T))
```

